version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=True
      - SECRET_KEY=your-production-secret-key-here
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 umpire_assigner.wsgi:application