# Generated by Django 5.2.6 on 2025-09-06 15:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
            },
        ),
        migrations.CreateModel(
            name="LeagueAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "League Admin",
                "verbose_name_plural": "League Admins",
            },
        ),
        migrations.CreateModel(
            name="PayRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solo_patched",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=6
                    ),
                ),
                (
                    "solo_unpatched",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("40.00"), max_digits=6
                    ),
                ),
                (
                    "plate_patched",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("35.00"), max_digits=6
                    ),
                ),
                (
                    "plate_unpatched",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("30.00"), max_digits=6
                    ),
                ),
                (
                    "base_unpatched",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("25.00"), max_digits=6
                    ),
                ),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Pay Rate",
                "verbose_name_plural": "Pay Rates",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Umpire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("adult", models.BooleanField(default=False)),
                ("patched", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Umpire",
                "verbose_name_plural": "Umpires",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("AAA", "AAA"),
                            ("Minors", "Minors"),
                            ("Majors", "Majors"),
                        ],
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assignments.coach",
                    ),
                ),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("8:00", "8:00 AM"),
                            ("10:15", "10:15 AM"),
                            ("12:30", "12:30 PM"),
                            ("2:45", "2:45 PM"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("A", "Field A"),
                            ("B", "Field B"),
                            ("C", "Field C"),
                            ("D", "Field D"),
                            ("E", "Field E"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "away_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_games",
                        to="assignments.team",
                    ),
                ),
                (
                    "home_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_games",
                        to="assignments.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Game",
                "verbose_name_plural": "Games",
                "ordering": ["date", "time", "field"],
                "unique_together": {("date", "time", "field")},
            },
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "league_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="assignments.leagueadmin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Town",
                "verbose_name_plural": "Towns",
            },
        ),
        migrations.AddField(
            model_name="team",
            name="town",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="assignments.town"
            ),
        ),
        migrations.CreateModel(
            name="UmpirePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("paid", models.BooleanField(default=False)),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "umpire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="assignments.umpire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umpire Payment",
                "verbose_name_plural": "Umpire Payments",
                "ordering": ["-period_end", "umpire"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("town", "level", "name")},
        ),
        migrations.CreateModel(
            name="UmpireAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("plate", "Plate Umpire"),
                            ("base", "Base Umpire"),
                            ("solo", "Solo Umpire"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "pay_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assignments.game",
                    ),
                ),
                (
                    "umpire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="assignments.umpire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Umpire Assignment",
                "verbose_name_plural": "Umpire Assignments",
                "unique_together": {("game", "umpire")},
            },
        ),
    ]
