# Generated by Django 5.2.6 on 2025-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0002_umpire_user_umpireavailability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="umpireavailability",
            options={
                "ordering": ["date", "time_slot", "umpire"],
                "verbose_name": "Umpire Availability",
                "verbose_name_plural": "Umpire Availabilities",
            },
        ),
        migrations.AlterUniqueTogether(
            name="umpireavailability",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="umpireavailability",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("8:00", "8:00 AM"),
                    ("10:15", "10:15 AM"),
                    ("12:30", "12:30 PM"),
                    ("2:45", "2:45 PM"),
                    ("all", "All Time Slots"),
                ],
                default="all",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="umpireavailability",
            unique_together={("umpire", "date", "time_slot")},
        ),
    ]
