# Generated by Django 5.2.6 on 2025-09-08 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0003_alter_umpireavailability_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="umpireavailability",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="umpireavailability",
            name="start_time",
        ),
    ]
