# Generated by Django 5.2.6 on 2025-09-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0004_remove_umpireavailability_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="umpire",
            name="is_assigner",
            field=models.BooleanField(
                default=False,
                help_text="External assigner service - can be booked for multiple games at same time",
            ),
        ),
    ]
