# Generated by Django 5.2.6 on 2025-09-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0005_umpire_is_assigner"),
    ]

    operations = [
        migrations.AddField(
            model_name="umpirepayment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("check", "Check"),
                    ("cash", "Cash"),
                    ("venmo", "Venmo"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="umpirepayment",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Payment details like check number, transaction ID, etc.",
            ),
        ),
    ]
