# Generated by Django 5.2.6 on 2025-09-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0006_umpirepayment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("completed", "Completed"),
                    ("postponed", "Postponed"),
                    ("cancelled", "Cancelled"),
                ],
                default="scheduled",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="umpireassignment",
            name="worked_status",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("worked", "Worked"),
                    ("no_show", "No Show"),
                    ("cancelled", "Cancelled"),
                ],
                default="assigned",
                max_length=20,
            ),
        ),
    ]
