# Generated by Django 5.0.2 on 2026-04-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0007_game_status_umpireassignment_worked_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
