# Generated by Django 5.0.2 on 2026-04-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0008_game_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:00", "8:00 AM"),
                    ("10:15", "10:15 AM"),
                    ("12:30", "12:30 PM"),
                    ("2:45", "2:45 PM"),
                    ("5:30", "5:30 PM"),
                    ("6:00", "6:00 PM"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="umpireavailability",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("8:00", "8:00 AM"),
                    ("10:15", "10:15 AM"),
                    ("12:30", "12:30 PM"),
                    ("2:45", "2:45 PM"),
                    ("5:30", "5:30 PM"),
                    ("6:00", "6:00 PM"),
                    ("all", "All Time Slots"),
                ],
                default="all",
                max_length=10,
            ),
        ),
    ]
