# Generated by Django 5.0.2 on 2026-04-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0009_add_evening_time_slots"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="field",
            field=models.CharField(
                choices=[
                    ("A", "Field A"),
                    ("B", "Field B"),
                    ("C", "Field C"),
                    ("D", "Field D"),
                    ("E", "Field E"),
                    ("Ames", "Ames St."),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:00", "8:00 AM"),
                    ("10:15", "10:15 AM"),
                    ("12:30", "12:30 PM"),
                    ("2:45", "2:45 PM"),
                    ("4:00", "4:00 PM"),
                    ("5:30", "5:30 PM"),
                    ("6:00", "6:00 PM"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="level",
            field=models.CharField(
                choices=[
                    ("AAA", "AAA"),
                    ("Minors", "Minors"),
                    ("Majors", "Majors"),
                    ("Softball", "Softball"),
                ],
                max_length=10,
            ),
        ),
    ]
