# Generated by Django 5.0.2 on 2026-04-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0010_increase_field_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="field",
            field=models.CharField(
                choices=[
                    ("A", "Field A"),
                    ("B", "Field B"),
                    ("C", "Field C"),
                    ("D", "Field D"),
                    ("E", "Field E"),
                    ("Ames", "Ames St."),
                    ("Sharon Middle School", "Sharon Middle School"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="level",
            field=models.CharField(
                choices=[
                    ("AAA", "AAA"),
                    ("Minors", "Minors"),
                    ("Majors", "Majors"),
                    ("Softball", "Softball"),
                    ("Junior", "Junior"),
                ],
                max_length=10,
            ),
        ),
    ]
