# Generated by Django 5.0.2 on 2026-06-10 02:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0006_set_assigner_flag"),
        ("assignments", "0011_add_sharon_middle_school_field"),
    ]

    operations = []
