# Generated by Django 5.0.2 on 2026-06-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0012_merge_20260609_2254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="time",
            field=models.CharField(
                choices=[
                    ("8:00", "8:00 AM"),
                    ("10:00", "10:00 AM"),
                    ("10:15", "10:15 AM"),
                    ("12:00", "12:00 PM"),
                    ("12:30", "12:30 PM"),
                    ("14:00", "2:00 PM"),
                    ("14:45", "2:45 PM"),
                    ("16:00", "4:00 PM"),
                    ("17:30", "5:30 PM"),
                    ("18:00", "6:00 PM"),
                    ("19:30", "7:30 PM"),
                    ("20:00", "8:00 PM"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="umpireavailability",
            name="time_slot",
            field=models.CharField(
                choices=[
                    ("8:00", "8:00 AM"),
                    ("10:00", "10:00 AM"),
                    ("10:15", "10:15 AM"),
                    ("12:00", "12:00 PM"),
                    ("12:30", "12:30 PM"),
                    ("14:00", "2:00 PM"),
                    ("14:45", "2:45 PM"),
                    ("16:00", "4:00 PM"),
                    ("17:30", "5:30 PM"),
                    ("18:00", "6:00 PM"),
                    ("19:30", "7:30 PM"),
                    ("20:00", "8:00 PM"),
                    ("all", "All Time Slots"),
                ],
                default="all",
                max_length=10,
            ),
        ),
    ]
