# Generated by Django 5.0.2 on 2026-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignments", "0014_convert_legacy_time_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="level",
            field=models.CharField(
                choices=[
                    ("AAA", "AAA"),
                    ("Minors", "Minors"),
                    ("Majors", "Majors"),
                    ("Softball", "Softball"),
                    ("Junior", "Junior"),
                    ("9u", "9u"),
                    ("10u", "10u"),
                    ("11u", "11u"),
                    ("12u", "12u"),
                    ("13u", "13u"),
                    ("14u", "14u"),
                    ("15u", "15u"),
                    ("16u", "16u"),
                ],
                max_length=10,
            ),
        ),
    ]
